### ISSUE TITLE
Just a head up

### ISSUE THREAD

**Issue by TylerTheLinuxDev** [sammonius/qtc#1]
When running CLOC (https://github.com/AlDanial/cloc) to count all of the lines of codes and files relevant to QT headers, it sums up to around 467,944 lines of C++ code and around 3357 files and that is excluding standard library aspects.

I think if you are really focused on wanting to bind QT project with Pure C API, then you may have to write a C++ to C transpiler leveraging Clang compiler or other compiler infrastructure that have the capability to parse C++. I don't think it's practical to try your hands on binding QT manually, because not only do you have to bind significant portion of QT, you also have to worry about extensibility part of QT IE how would C programmers inherit QT objects and extend the implementation? There is also the consideration of having to update binding as QT code changes over time.

I would say writing a GUI Toolkit from scratch using C to be an easier endeavor than trying to bind QT which is a C++ project.

Wish you all the best.

**Comment by TylerTheLinuxDev** [comment]
If you could hop on Element (https://element.io/) and join up in "Pure C" room, I'd be happy to walk you through on some of the aspects involved this project. Pure C Room: https://matrix.to/#/#purec:matrix.org

**Comment by sammonius** [comment]
Thanks, but I only want to bind the GUI portion of Qt. I think you're right about it being impractical to try to bind it manually because a lot of it is repetitive. I'm going to try to automate it by creating a system similar to Q_PROPERTY() that generates the bindings to try to speed this up.
